In [6]:
!pip install streamlit

Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (1.36.0)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.25.2)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.0.3)
Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (14.0.2)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)
Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.12.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)
Requirement already satisfied: watchdog<5,>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.0.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.2)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.6.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import os
os.chdir('/content/drive/MyDrive/Python/bread')

In [9]:
from google.colab import files
files.view("test.py")

In [ ]:
!streamlit run test.py & sleep 3 && npx localtunnel --port 8501

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.105.17.55:8501

npx: installed 22 in 4.362s
your url is: https://pretty-terms-mix.loca.lt
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
2024-07-07 04:59:41.105 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/content/drive/MyDrive/Python/bread/test.py", line 91, in <module>
    value_df =pd.DataFream([WeatherValue,EventValue,TemperatureValue],index=['Event','Temperature','Weather']).T
AttributeError: module 'pandas' has no attribute 'DataFream'
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
2024-07-07 05:04:42.265 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/content/drive/MyDrive/Python/bread/test.py", line 91, in <module>
    value_df = pd.DataFream([WeatherValue,EventValue,TemperatureValue],index=['Event','Temperature','Weather']).T
AttributeError: module 'pandas' has no attribute 'DataFream'
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
2024-07-07 05:04:51.263 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/content/drive/MyDrive/Python/bread/test.py", line 91, in <module>
    value_df = pd.DataFream([WeatherValue,EventValue,TemperatureValue],index=['Event','Temperature','Weather']).T
AttributeError: module 'pandas' has no attribute 'DataFream'
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
2024-07-07 05:24:02.561 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/content/drive/MyDrive/Python/bread/test.py", line 92, in <module>
    value_df = pd.DataFream([WeatherValue,EventValue,TemperatureValue],index=['Event','Temperature','Weather']).T
AttributeError: module 'pandas' has no attribute 'DataFream'
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
2024-07-07 05:27:12.778 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/content/drive/MyDrive/Python/bread/test.py", line 84, in <module>
    value_df = pd.DataFream([WeatherValue,EventValue,TemperatureValue],index=['Event','Temperature','Weather']).T
AttributeError: module 'pandas' has no attribute 'DataFream'
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]
Index(['Date', 'Unnamed: 1', 'Event', 'Temperature', 'Unnamed: 4', 'Weather',
       'Day', '食パン', 'フランスパン', 'タルティーヌ', 'メロンパン', 'あんぱん', 'スコーン'],
      dtype='object')
0     2
1     1
2     3
3     3
4     1
5     2
6     2
7     1
8     3
9     1
10    2
11    2
12    3
13    3
14    1
15    2
16    2
17    3
18    3
19    1
20    2
21    2
22    3
23    1
24    1
25    1
26    2
27    1
28    3
29    1
Name: Weather, dtype: int64
   Date Unnamed: 1  Event  Temperature Unnamed: 4  Weather  ... 食パン  フランスパン  タルティーヌ  メロンパン  あんぱん  スコーン
0  6月1日         あり      2           28     cloudy        2  ...   5       5      30     10     5     8
1  6月2日         なし      1           25      sunny        1  ...  20       5      20     16     6    10
2  6月3日         なし      1           29       rain        3  ...  15       5      19     17     8    16
3  6月4日         あり      2           31       rain        3  ...   7       3      15      8     6     8
4  6月5日         あり      2           32      sunny        1  ...   8       2      13     10     8     9

[5 rows x 13 columns]